# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "EasyMapParser"
description = "Easy Map Parser"
include-before = [
	"configurations.cmake"
]

[subdir.test]

[target.EasyMapParserLib]
type = "library"
headers = ["include/**.h"]
sources = ["src/**.cpp", "src/**.h"]
include-directories = ["include"]
compile-features = ["cxx_std_20"]
